spring:
  application:
    name: InMap

  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=InMap
    url: jdbc:mysql://localhost:3306/InMap
    username: SA
    password: A1b@Cd3#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8070
