spring:
  application:
    name: InMap

  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=InMap
    url: jdbc:mysql://localhost:3306/InMap
    username: SA
    password: A1b@Cd3#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8070

logging:
  level:
    com.mchtcavas.InMap: DEBUG
    root: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  nearby-template:
    # key: google
    key: mock
  google:
    api:
      base-url: https://maps.googleapis.com/maps/api/place/nearbysearch/json
      key: YOUR_API_KEY
  mock:
    api:
      base-url: https://mocki.io/v1/120a45f3-0643-4ae7-b035-436d6c5dca7c

